# Generated by Django 4.2.20 on 2026-03-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
