# Generated by Django 4.2.20 on 2026-03-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_updated_at_userinfo_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='Co',
            field=models.FloatField(verbose_name='Co'),
        ),
    ]
